{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance_ip",
    "label": "instance_ip",
    "query": {
     "query": "query_result(count(container_memory_usage_bytes{image!=\"\"}) by (instance))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Usage (%) - /",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\r\n  node_filesystem_avail_bytes{mountpoint=\"/\", fstype!~\"tmpfs|aufs|overlay\", instance=~\"${instance_ip}:.*\"} * 100\r\n  /\r\n  node_filesystem_size_bytes{mountpoint=\"/\", fstype!~\"tmpfs|aufs|overlay\", instance=~\"${instance_ip}:.*\"}\r\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPUutilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"${instance_ip}:.*\"}[1m])) * 100)\r\n",
     "legendFormat": "CPU Usage - {{instance}}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"${instance_ip}:.*\"} - node_memory_MemAvailable_bytes{instance=~\"${instance_ip}:.*\"})\r\n / node_memory_MemTotal_bytes{instance=~\"${instance_ip}:.*\"}) * 100\r\n",
     "legendFormat": "RAM Usage - {{instance}}"
    }
   ]
  }
 ]
}