groups:
  - name: container_rules
    interval: 30s
    rules:
      - record: container_recently_running
        expr: |
          count(container_memory_usage_bytes{container!="", image!=""}) by (instance)
